database_uri: "mongodb://localhost:27017/Chatbot"
database_username: "root"
database_password: "root"
contacts_database_name: "contacts"
debug: true
port: 5000
host: "0.0.0.0"
session_dead_threshold_in_sec: 600
